version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.1.0

restore_cache: &restorecache
  keys:
    - v1-dependencies-{{ checksum "yarn.lock" }}
    - v1-dependencies-

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - <<: *restorecache
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn build
  unit-tests:
    <<: *defaults
    steps:
      - checkout
      - <<: *restorecache
      - run: yarn test
  style-check:
    name: Style check
    <<: *defaults
    steps:
      - checkout
      - <<: *restorecache
      - run: yarn run style
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit-tests:
          requires:
            - build
      - style-check:
          requires:
            - build
